name: Deploy to ECR

on: 
  push:
    branches: main

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    # Add this step to list files in the repository for debugging
    - name: List files
      run: ls -al

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1
        
    - name: Build, test, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: my-app-repo
        IMAGE_TAG: v0.1
      run: |
        # Docker build using the standard Dockerfile
        docker build -t $ECR_REGISTRY/my-app-repo:webapp-$IMAGE_TAG -f Dockerfile .
        # Docker push for the standard Dockerfile image
        docker push $ECR_REGISTRY/my-app-repo:webapp-$IMAGE_TAG
        
        # Docker build using Dockerfile_mysql
        docker build -t $ECR_REGISTRY/my-mysql-repo:mysql-$IMAGE_TAG -f Dockerfile_mysql .
        # Docker push for the Dockerfile_mysql image
        docker push $ECR_REGISTRY/my-mysql-repo:mysql-$IMAGE_TAG
